services:
  # docker-windscribe:
  #   image: wiorca/docker-windscribe
  #   container_name: docker-windscribe
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/London
  #     - WINDSCRIBE_USERNAME=gunnithan
  #     - WINDSCRIBE_PASSWORD=CHu&!r&9BRjR%M
  #     - WINDSCRIBE_PROTOCOL=udp
  #     - WINDSCRIBE_PORT=80
  #     - WINDSCRIBE_LOCATION=London
  #     - WINDSCRIBE_LANBYPASS=on
  #     - WINDSCRIBE_FIREWALL=on
  #     - VPN_PORT=9999
  #   volumes:
  #     - /location/on/host:/config
  #   dns:
  #     - 8.8.8.8
  #   cap_add:
  #     - NET_ADMIN
  #   devices:
  #     - /dev/net/tun:/dev/net/tun
  #   ports:
  #     - 8080:8080 # port for qbittorrent
  #   restart: unless-stopped


  # gluetun:
  #   image: qmcgaw/gluetun
  #   container_name: gluetun
  #   cap_add:
  #     - NET_ADMIN
  #   devices:
  #     - /dev/net/tun:/dev/net/tun
  #   ports:
  #     - 8080:8080 # port for qbittorrent
  #     - 6881:6881
  #   volumes:
  #     - ./gluetun:/gluetun
  #   environment:
  #     - PUID=1000 # Set this to your restricted docker user ID and group ID, otherwise ignore these environment variables
  #     - PGID=1000
  #     - VPN_SERVICE_PROVIDER=windscribe
  #     - VPN_TYPE=wireguard
  #     - WIREGUARD_PRIVATE_KEY=+NXNOR3ImkApY5ggL9JJfywQxirUmTGTxfyomw+90UA=
  #     - WIREGUARD_PUBLIC_KEY=qWSr7Tf40kvS+0kv4TbpSb6EevhSvn3kuXsjn2eWbA4=
  #     - WIREGUARD_ADDRESSES=100.89.85.58/32
  #     - WIREGUARD_PRESHARED_KEY=KleVZsLH6M44xwn1TxwPSX+8cVUZ5JcqTr/STMnKqXI=
  #     - SERVER_REGIONS=United Kingdom
  #     - UPDATER_PERIOD=24h
  #     - TZ=Europe/London

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    #network_mode: service:docker-windscribe
    #network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./config:/config
      - /home/unnit/Downloads:/downloads #optional
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    # depends_on:
    #   gluetun:
    #     condition: service_healthy
    restart: unless-stopped
